# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(684, 1036)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stack = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stack.sizePolicy().hasHeightForWidth())
        self.stack.setSizePolicy(sizePolicy)
        self.stack.setObjectName("stack")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_main)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_shortcuts = QtWidgets.QPushButton(self.page_main)
        self.pushButton_shortcuts.setObjectName("pushButton_shortcuts")
        self.verticalLayout.addWidget(self.pushButton_shortcuts)
        self.box_database = QtWidgets.QGroupBox(self.page_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_database.sizePolicy().hasHeightForWidth())
        self.box_database.setSizePolicy(sizePolicy)
        self.box_database.setObjectName("box_database")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.box_database)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_dbid = QtWidgets.QLabel(self.box_database)
        self.label_dbid.setObjectName("label_dbid")
        self.horizontalLayout_8.addWidget(self.label_dbid)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.lineEdit_dbid = QtWidgets.QLineEdit(self.box_database)
        self.lineEdit_dbid.setObjectName("lineEdit_dbid")
        self.horizontalLayout_8.addWidget(self.lineEdit_dbid)
        self.checkBox_dbid = QtWidgets.QCheckBox(self.box_database)
        self.checkBox_dbid.setObjectName("checkBox_dbid")
        self.horizontalLayout_8.addWidget(self.checkBox_dbid)
        self.gridLayout_13.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.frame_box = QtWidgets.QFrame(self.box_database)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_box.sizePolicy().hasHeightForWidth())
        self.frame_box.setSizePolicy(sizePolicy)
        self.frame_box.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_box.setObjectName("frame_box")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_box)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_13.addWidget(self.frame_box, 1, 0, 1, 1)
        self.pushButton_dbsetting = QtWidgets.QPushButton(self.box_database)
        self.pushButton_dbsetting.setObjectName("pushButton_dbsetting")
        self.gridLayout_13.addWidget(self.pushButton_dbsetting, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.box_database)
        self.box_pupil = QtWidgets.QGroupBox(self.page_main)
        self.box_pupil.setObjectName("box_pupil")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.box_pupil)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_pupiltimer = QtWidgets.QLabel(self.box_pupil)
        self.label_pupiltimer.setObjectName("label_pupiltimer")
        self.horizontalLayout_3.addWidget(self.label_pupiltimer)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lineEdit_pupiltimer = QtWidgets.QLineEdit(self.box_pupil)
        self.lineEdit_pupiltimer.setObjectName("lineEdit_pupiltimer")
        self.horizontalLayout_3.addWidget(self.lineEdit_pupiltimer)
        self.label_pupilunit = QtWidgets.QLabel(self.box_pupil)
        self.label_pupilunit.setObjectName("label_pupilunit")
        self.horizontalLayout_3.addWidget(self.label_pupilunit)
        self.verticalLayout.addWidget(self.box_pupil)
        self.box_sequence = QtWidgets.QGroupBox(self.page_main)
        self.box_sequence.setObjectName("box_sequence")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.box_sequence)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_seqsize = QtWidgets.QLabel(self.box_sequence)
        self.label_seqsize.setObjectName("label_seqsize")
        self.horizontalLayout_6.addWidget(self.label_seqsize)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.lineEdit_seqsize = QtWidgets.QLineEdit(self.box_sequence)
        self.lineEdit_seqsize.setObjectName("lineEdit_seqsize")
        self.horizontalLayout_6.addWidget(self.lineEdit_seqsize)
        self.pushButton_seqsize = QtWidgets.QPushButton(self.box_sequence)
        self.pushButton_seqsize.setObjectName("pushButton_seqsize")
        self.horizontalLayout_6.addWidget(self.pushButton_seqsize)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.box_detailed = QtWidgets.QGroupBox(self.box_sequence)
        self.box_detailed.setObjectName("box_detailed")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.box_detailed)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_seq0 = QtWidgets.QLineEdit(self.box_detailed)
        self.lineEdit_seq0.setObjectName("lineEdit_seq0")
        self.horizontalLayout_7.addWidget(self.lineEdit_seq0)
        self.lineEdit_seq1 = QtWidgets.QLineEdit(self.box_detailed)
        self.lineEdit_seq1.setObjectName("lineEdit_seq1")
        self.horizontalLayout_7.addWidget(self.lineEdit_seq1)
        self.lineEdit_seq2 = QtWidgets.QLineEdit(self.box_detailed)
        self.lineEdit_seq2.setObjectName("lineEdit_seq2")
        self.horizontalLayout_7.addWidget(self.lineEdit_seq2)
        self.lineEdit_seq3 = QtWidgets.QLineEdit(self.box_detailed)
        self.lineEdit_seq3.setObjectName("lineEdit_seq3")
        self.horizontalLayout_7.addWidget(self.lineEdit_seq3)
        self.lineEdit_seq4 = QtWidgets.QLineEdit(self.box_detailed)
        self.lineEdit_seq4.setObjectName("lineEdit_seq4")
        self.horizontalLayout_7.addWidget(self.lineEdit_seq4)
        self.lineEdit_seq5 = QtWidgets.QLineEdit(self.box_detailed)
        self.lineEdit_seq5.setObjectName("lineEdit_seq5")
        self.horizontalLayout_7.addWidget(self.lineEdit_seq5)
        self.lineEdit_seq6 = QtWidgets.QLineEdit(self.box_detailed)
        self.lineEdit_seq6.setObjectName("lineEdit_seq6")
        self.horizontalLayout_7.addWidget(self.lineEdit_seq6)
        self.lineEdit_seq7 = QtWidgets.QLineEdit(self.box_detailed)
        self.lineEdit_seq7.setObjectName("lineEdit_seq7")
        self.horizontalLayout_7.addWidget(self.lineEdit_seq7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addWidget(self.box_detailed)
        self.verticalLayout.addWidget(self.box_sequence)
        self.box_game = QtWidgets.QGroupBox(self.page_main)
        self.box_game.setObjectName("box_game")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.box_game)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_boardsize = QtWidgets.QLabel(self.box_game)
        self.label_boardsize.setObjectName("label_boardsize")
        self.horizontalLayout_4.addWidget(self.label_boardsize)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.lineEdit_boardsizen = QtWidgets.QLineEdit(self.box_game)
        self.lineEdit_boardsizen.setObjectName("lineEdit_boardsizen")
        self.horizontalLayout_4.addWidget(self.lineEdit_boardsizen)
        self.label_5 = QtWidgets.QLabel(self.box_game)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.lineEdit_boardsizem = QtWidgets.QLineEdit(self.box_game)
        self.lineEdit_boardsizem.setObjectName("lineEdit_boardsizem")
        self.horizontalLayout_4.addWidget(self.lineEdit_boardsizem)
        self.pushButton_boardsize = QtWidgets.QPushButton(self.box_game)
        self.pushButton_boardsize.setObjectName("pushButton_boardsize")
        self.horizontalLayout_4.addWidget(self.pushButton_boardsize)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.box_board = QtWidgets.QGroupBox(self.box_game)
        self.box_board.setObjectName("box_board")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.box_board)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.lineEdit_board02 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board02.setObjectName("lineEdit_board02")
        self.gridLayout_15.addWidget(self.lineEdit_board02, 1, 2, 1, 1)
        self.lineEdit_board04 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board04.setObjectName("lineEdit_board04")
        self.gridLayout_15.addWidget(self.lineEdit_board04, 1, 4, 1, 1)
        self.lineEdit_board03 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board03.setObjectName("lineEdit_board03")
        self.gridLayout_15.addWidget(self.lineEdit_board03, 1, 3, 1, 1)
        self.lineEdit_board01 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board01.setObjectName("lineEdit_board01")
        self.gridLayout_15.addWidget(self.lineEdit_board01, 1, 1, 1, 1)
        self.lineEdit_board00 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board00.setObjectName("lineEdit_board00")
        self.gridLayout_15.addWidget(self.lineEdit_board00, 1, 0, 1, 1)
        self.lineEdit_board10 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board10.setObjectName("lineEdit_board10")
        self.gridLayout_15.addWidget(self.lineEdit_board10, 2, 0, 1, 1)
        self.lineEdit_board11 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board11.setObjectName("lineEdit_board11")
        self.gridLayout_15.addWidget(self.lineEdit_board11, 2, 1, 1, 1)
        self.lineEdit_board24 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board24.setObjectName("lineEdit_board24")
        self.gridLayout_15.addWidget(self.lineEdit_board24, 3, 4, 1, 1)
        self.lineEdit_board14 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board14.setObjectName("lineEdit_board14")
        self.gridLayout_15.addWidget(self.lineEdit_board14, 2, 4, 1, 1)
        self.lineEdit_board21 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board21.setObjectName("lineEdit_board21")
        self.gridLayout_15.addWidget(self.lineEdit_board21, 3, 1, 1, 1)
        self.lineEdit_board23 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board23.setObjectName("lineEdit_board23")
        self.gridLayout_15.addWidget(self.lineEdit_board23, 3, 3, 1, 1)
        self.lineEdit_board20 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board20.setObjectName("lineEdit_board20")
        self.gridLayout_15.addWidget(self.lineEdit_board20, 3, 0, 1, 1)
        self.lineEdit_board22 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board22.setObjectName("lineEdit_board22")
        self.gridLayout_15.addWidget(self.lineEdit_board22, 3, 2, 1, 1)
        self.lineEdit_board31 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board31.setObjectName("lineEdit_board31")
        self.gridLayout_15.addWidget(self.lineEdit_board31, 4, 1, 1, 1)
        self.lineEdit_board32 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board32.setObjectName("lineEdit_board32")
        self.gridLayout_15.addWidget(self.lineEdit_board32, 4, 2, 1, 1)
        self.lineEdit_board30 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board30.setObjectName("lineEdit_board30")
        self.gridLayout_15.addWidget(self.lineEdit_board30, 4, 0, 1, 1)
        self.lineEdit_board33 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board33.setObjectName("lineEdit_board33")
        self.gridLayout_15.addWidget(self.lineEdit_board33, 4, 3, 1, 1)
        self.lineEdit_board34 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board34.setObjectName("lineEdit_board34")
        self.gridLayout_15.addWidget(self.lineEdit_board34, 4, 4, 1, 1)
        self.lineEdit_board13 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board13.setObjectName("lineEdit_board13")
        self.gridLayout_15.addWidget(self.lineEdit_board13, 2, 3, 1, 1)
        self.lineEdit_board12 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board12.setObjectName("lineEdit_board12")
        self.gridLayout_15.addWidget(self.lineEdit_board12, 2, 2, 1, 1)
        self.lineEdit_board40 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board40.setObjectName("lineEdit_board40")
        self.gridLayout_15.addWidget(self.lineEdit_board40, 5, 0, 1, 1)
        self.lineEdit_board41 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board41.setObjectName("lineEdit_board41")
        self.gridLayout_15.addWidget(self.lineEdit_board41, 5, 1, 1, 1)
        self.lineEdit_board42 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board42.setObjectName("lineEdit_board42")
        self.gridLayout_15.addWidget(self.lineEdit_board42, 5, 2, 1, 1)
        self.lineEdit_board43 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board43.setObjectName("lineEdit_board43")
        self.gridLayout_15.addWidget(self.lineEdit_board43, 5, 3, 1, 1)
        self.lineEdit_board44 = QtWidgets.QLineEdit(self.box_board)
        self.lineEdit_board44.setObjectName("lineEdit_board44")
        self.gridLayout_15.addWidget(self.lineEdit_board44, 5, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.box_board)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_dwell = QtWidgets.QLabel(self.box_game)
        self.label_dwell.setObjectName("label_dwell")
        self.horizontalLayout_5.addWidget(self.label_dwell)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.lineEdit_dwell = QtWidgets.QLineEdit(self.box_game)
        self.lineEdit_dwell.setObjectName("lineEdit_dwell")
        self.horizontalLayout_5.addWidget(self.lineEdit_dwell)
        self.label_dwellunit = QtWidgets.QLabel(self.box_game)
        self.label_dwellunit.setObjectName("label_dwellunit")
        self.horizontalLayout_5.addWidget(self.label_dwellunit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.box_game)
        self.frame_bubble = QtWidgets.QFrame(self.page_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_bubble.sizePolicy().hasHeightForWidth())
        self.frame_bubble.setSizePolicy(sizePolicy)
        self.frame_bubble.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bubble.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bubble.setObjectName("frame_bubble")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_bubble)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.hLayout_bubble = QtWidgets.QHBoxLayout()
        self.hLayout_bubble.setObjectName("hLayout_bubble")
        self.label_bubble = QtWidgets.QLabel(self.frame_bubble)
        self.label_bubble.setObjectName("label_bubble")
        self.hLayout_bubble.addWidget(self.label_bubble)
        self.pushButton_bubble = QtWidgets.QPushButton(self.frame_bubble)
        self.pushButton_bubble.setObjectName("pushButton_bubble")
        self.hLayout_bubble.addWidget(self.pushButton_bubble)
        self.gridLayout_7.addLayout(self.hLayout_bubble, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_bubble)
        self.pushButton_start = QtWidgets.QPushButton(self.page_main)
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout.addWidget(self.pushButton_start)
        self.stack.addWidget(self.page_main)
        self.page_database = QtWidgets.QWidget()
        self.page_database.setObjectName("page_database")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_database)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.box_setting = QtWidgets.QGroupBox(self.page_database)
        self.box_setting.setObjectName("box_setting")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.box_setting)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.table = QtWidgets.QTableWidget(self.box_setting)
        self.table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table.setShowGrid(True)
        self.table.setGridStyle(QtCore.Qt.SolidLine)
        self.table.setWordWrap(True)
        self.table.setCornerButtonEnabled(True)
        self.table.setObjectName("table")
        self.table.setColumnCount(1)
        self.table.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        self.gridLayout_6.addWidget(self.table, 0, 0, 1, 1)
        self.hLayout_setting = QtWidgets.QHBoxLayout()
        self.hLayout_setting.setObjectName("hLayout_setting")
        self.pushButton_cancel = QtWidgets.QPushButton(self.box_setting)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.hLayout_setting.addWidget(self.pushButton_cancel)
        self.pushButton_apply = QtWidgets.QPushButton(self.box_setting)
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.hLayout_setting.addWidget(self.pushButton_apply)
        self.gridLayout_6.addLayout(self.hLayout_setting, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem5, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.box_setting, 0, 0, 1, 1)
        self.stack.addWidget(self.page_database)
        self.page_shortcuts = QtWidgets.QWidget()
        self.page_shortcuts.setObjectName("page_shortcuts")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_shortcuts)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.box_shortcuts = QtWidgets.QGroupBox(self.page_shortcuts)
        self.box_shortcuts.setObjectName("box_shortcuts")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.box_shortcuts)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.vLayout_shortcuts = QtWidgets.QVBoxLayout()
        self.vLayout_shortcuts.setObjectName("vLayout_shortcuts")
        self.hLayout_shortcut1 = QtWidgets.QHBoxLayout()
        self.hLayout_shortcut1.setContentsMargins(10, -1, 10, -1)
        self.hLayout_shortcut1.setObjectName("hLayout_shortcut1")
        self.label_shortcut1Name = QtWidgets.QLabel(self.box_shortcuts)
        self.label_shortcut1Name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_shortcut1Name.setObjectName("label_shortcut1Name")
        self.hLayout_shortcut1.addWidget(self.label_shortcut1Name)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_shortcut1.addItem(spacerItem6)
        self.label_shortcut1 = QtWidgets.QLabel(self.box_shortcuts)
        self.label_shortcut1.setObjectName("label_shortcut1")
        self.hLayout_shortcut1.addWidget(self.label_shortcut1)
        self.vLayout_shortcuts.addLayout(self.hLayout_shortcut1)
        self.hLayout_shortcut2 = QtWidgets.QHBoxLayout()
        self.hLayout_shortcut2.setContentsMargins(10, -1, 10, -1)
        self.hLayout_shortcut2.setObjectName("hLayout_shortcut2")
        self.label_shortcut2Name = QtWidgets.QLabel(self.box_shortcuts)
        self.label_shortcut2Name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_shortcut2Name.setObjectName("label_shortcut2Name")
        self.hLayout_shortcut2.addWidget(self.label_shortcut2Name)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_shortcut2.addItem(spacerItem7)
        self.label_shortcut2 = QtWidgets.QLabel(self.box_shortcuts)
        self.label_shortcut2.setObjectName("label_shortcut2")
        self.hLayout_shortcut2.addWidget(self.label_shortcut2)
        self.vLayout_shortcuts.addLayout(self.hLayout_shortcut2)
        self.pushButton_ok = QtWidgets.QPushButton(self.box_shortcuts)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.vLayout_shortcuts.addWidget(self.pushButton_ok)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vLayout_shortcuts.addItem(spacerItem8)
        self.gridLayout_5.addLayout(self.vLayout_shortcuts, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.box_shortcuts, 0, 0, 1, 1)
        self.stack.addWidget(self.page_shortcuts)
        self.horizontalLayout_2.addWidget(self.stack)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GazeGame"))
        self.pushButton_shortcuts.setText(_translate("MainWindow", "Shortcuts"))
        self.box_database.setTitle(_translate("MainWindow", "Database"))
        self.label_dbid.setText(_translate("MainWindow", "ID:"))
        self.checkBox_dbid.setText(_translate("MainWindow", "Apply"))
        self.pushButton_dbsetting.setText(_translate("MainWindow", "Database Setting"))
        self.box_pupil.setTitle(_translate("MainWindow", "Pupil Setting"))
        self.label_pupiltimer.setText(_translate("MainWindow", "Timer:"))
        self.label_pupilunit.setText(_translate("MainWindow", "second(s)"))
        self.box_sequence.setTitle(_translate("MainWindow", "Sequence Setting"))
        self.label_seqsize.setText(_translate("MainWindow", "Size:"))
        self.pushButton_seqsize.setText(_translate("MainWindow", "Apply"))
        self.box_detailed.setTitle(_translate("MainWindow", "Sequence"))
        self.box_game.setTitle(_translate("MainWindow", "Game Setting"))
        self.label_boardsize.setText(_translate("MainWindow", "Size:"))
        self.label_5.setText(_translate("MainWindow", "x"))
        self.pushButton_boardsize.setText(_translate("MainWindow", "Apply"))
        self.box_board.setTitle(_translate("MainWindow", "Board Setting"))
        self.label_dwell.setText(_translate("MainWindow", "Dwell Timer:"))
        self.label_dwellunit.setText(_translate("MainWindow", "second(s)"))
        self.label_bubble.setText(_translate("MainWindow", "Gaze Visalizaition"))
        self.pushButton_bubble.setText(_translate("MainWindow", "on / off"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.box_setting.setTitle(_translate("MainWindow", "Database Setting"))
        self.table.setSortingEnabled(False)
        item = self.table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Host"))
        item = self.table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "USER"))
        item = self.table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "PASSWORD"))
        item = self.table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "DB_NAME"))
        item = self.table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "CHARSET"))
        item = self.table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "TABLE"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Setting"))
        self.pushButton_cancel.setText(_translate("MainWindow", "CANCEL"))
        self.pushButton_apply.setText(_translate("MainWindow", "Apply"))
        self.box_shortcuts.setTitle(_translate("MainWindow", "Shortcuts"))
        self.label_shortcut1Name.setText(_translate("MainWindow", "Gaze Visualization\n"
"(On/Off)"))
        self.label_shortcut1.setText(_translate("MainWindow", "1"))
        self.label_shortcut2Name.setText(_translate("MainWindow", "Gaze Tracking\n"
"(Start/End)"))
        self.label_shortcut2.setText(_translate("MainWindow", "2"))
        self.pushButton_ok.setText(_translate("MainWindow", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
